/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ParticipantAdded = ContractEventLog<{
  participant: string;
  timestamp: string;
  0: string;
  1: string;
}>;
export type PowerLogged = ContractEventLog<{
  resource: string;
  timestamp: string;
  dayConsumption: string;
  dayProduction: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type ResourceAdded = ContractEventLog<{
  participant: string;
  resource: string;
  timestamp: string;
  resourceType: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type RoleAdminChanged = ContractEventLog<{
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleGranted = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleRevoked = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;

export interface APEnergy extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): APEnergy;
  clone(): APEnergy;
  methods: {
    DEFAULT_ADMIN_ROLE(): NonPayableTransactionObject<string>;

    addParticipant(): NonPayableTransactionObject<void>;

    addResource(
      _resourceAddress: string,
      _resourceType: string
    ): NonPayableTransactionObject<void>;

    getParticipantResources(
      _participantAddress: string
    ): NonPayableTransactionObject<string[]>;

    getParticipants(): NonPayableTransactionObject<string[]>;

    getResourcePowerConsumption(
      _resource: string
    ): NonPayableTransactionObject<[string, string, string][]>;

    getRoleAdmin(role: string | number[]): NonPayableTransactionObject<string>;

    grantRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    hasRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<boolean>;

    logPowerConsumption(
      _timestamp: number | string | BN,
      _dayConsumption: string,
      _dayProduction: string
    ): NonPayableTransactionObject<void>;

    participants(
      arg0: number | string | BN
    ): NonPayableTransactionObject<string>;

    renounceRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    revokeRole(
      role: string | number[],
      account: string
    ): NonPayableTransactionObject<void>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    ParticipantAdded(cb?: Callback<ParticipantAdded>): EventEmitter;
    ParticipantAdded(
      options?: EventOptions,
      cb?: Callback<ParticipantAdded>
    ): EventEmitter;

    PowerLogged(cb?: Callback<PowerLogged>): EventEmitter;
    PowerLogged(
      options?: EventOptions,
      cb?: Callback<PowerLogged>
    ): EventEmitter;

    ResourceAdded(cb?: Callback<ResourceAdded>): EventEmitter;
    ResourceAdded(
      options?: EventOptions,
      cb?: Callback<ResourceAdded>
    ): EventEmitter;

    RoleAdminChanged(cb?: Callback<RoleAdminChanged>): EventEmitter;
    RoleAdminChanged(
      options?: EventOptions,
      cb?: Callback<RoleAdminChanged>
    ): EventEmitter;

    RoleGranted(cb?: Callback<RoleGranted>): EventEmitter;
    RoleGranted(
      options?: EventOptions,
      cb?: Callback<RoleGranted>
    ): EventEmitter;

    RoleRevoked(cb?: Callback<RoleRevoked>): EventEmitter;
    RoleRevoked(
      options?: EventOptions,
      cb?: Callback<RoleRevoked>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "ParticipantAdded", cb: Callback<ParticipantAdded>): void;
  once(
    event: "ParticipantAdded",
    options: EventOptions,
    cb: Callback<ParticipantAdded>
  ): void;

  once(event: "PowerLogged", cb: Callback<PowerLogged>): void;
  once(
    event: "PowerLogged",
    options: EventOptions,
    cb: Callback<PowerLogged>
  ): void;

  once(event: "ResourceAdded", cb: Callback<ResourceAdded>): void;
  once(
    event: "ResourceAdded",
    options: EventOptions,
    cb: Callback<ResourceAdded>
  ): void;

  once(event: "RoleAdminChanged", cb: Callback<RoleAdminChanged>): void;
  once(
    event: "RoleAdminChanged",
    options: EventOptions,
    cb: Callback<RoleAdminChanged>
  ): void;

  once(event: "RoleGranted", cb: Callback<RoleGranted>): void;
  once(
    event: "RoleGranted",
    options: EventOptions,
    cb: Callback<RoleGranted>
  ): void;

  once(event: "RoleRevoked", cb: Callback<RoleRevoked>): void;
  once(
    event: "RoleRevoked",
    options: EventOptions,
    cb: Callback<RoleRevoked>
  ): void;
}
